### ISSUE TITLE
前往随机up失败,出现超时错误

### ISSUE THREAD

**Issue by catlair** [catlair/bili-task-puppeteer#1]
错误详情:
忘记映射logs文件夹, 显示错误如下
```
[2021-03-24T23:14:43.121] [WARN] upTask - 前往随机up失败 waiting for selector `.follow-content.section:not(.loading)` failed: timeout 13000ms exceeded
```

![Snipaste_2021-03-24_23-09-08](https://user-images.githubusercontent.com/44313800/112336062-b4057780-8cf7-11eb-80fe-94dea1cbdf80.png)

**Comment by catlair** [comment]
尝试对错误进行复现却无果, 暂时不知道原因, 无法进一步的观察

**Comment by catlair** [comment]
尝试对错误进行复现却无果, 暂时不知道原因, 无法进一步的观察
暂时处理方法是保留之前获取的Element列表，以备当获取失败时使用

**Comment by KudouRan** [comment]
出现上面错误后截图显示，page并不是关注列表页面，而是如下页面，所以无法找到关注列表。故上面的解决办法无效
![image](https://user-images.githubusercontent.com/81743795/115955401-c65a1780-a528-11eb-8343-a37032b369cb.png)
